clc;
clear all;
close all;
calculatorimage = imread("C:\Users\NANI NITHIN\Downloads\ip project.jpg");
figure;
subplot(2,2,1);
imshow(calculatorimage);
title('image of a calculator');
calculatorimage2 = rgb2gray(calculatorimage);
subplot(2,2,2);
imshow(calculatorimage2);
title('image in gray scale');
seenimage = imread("C:\Users\NANI NITHIN\Downloads\ip project 4.jpeg");
subplot(2,2,3);
imshow(seenimage);
title('clutter image of calulator and other objects');
seenimage2 = rgb2gray(seenimage);
subplot(2,2,4);
imshow(seenimage2);
title('image in gray scale');
calculatorpoints = detectSURFFeatures(calculatorimage2);
seenimagepoints = detectSURFFeatures(seenimage2);
figure;
subplot(2,1,1);
imshow(calculatorimage2);
title('100 strongest feature points from calculator image');
hold on;
plot(selectStrongest(calculatorpoints,100));
subplot(2,1,2);
imshow(seenimage2);
title('300 strong feature points of seen image');
hold on;
plot(selectStrongest(seenimagepoints,300));
[calculatorfeatures, calculatorpoints] = extractFeatures(calculatorimage2,calculatorpoints);
[seenfeatures, seenimagepoints] = extractFeatures(seenimage2,seenimagepoints);
calculatorpairs = matchFeatures(calculatorfeatures,seenfeatures);
matchedcalculatorpoints = calculatorpoints(calculatorpairs(:, 1), :);
matchedseenpoints = seenimagepoints(calculatorpairs(:, 2), :);
figure;
showMatchedFeatures(calculatorimage2, seenimage2, matchedcalculatorpoints, matchedseenpoints, 'montage');
title('matching the features in both the images');
[tform, inliercalculatorpoints, inlierseenpoints] = estimateGeometricTransform(matchedcalculatorpoints, matchedseenpoints,'affine');
figure;
showMatchedFeatures(calculatorimage2, seenimage2, inliercalculatorpoints, inlierseenpoints, 'montage');
title('matched points inliers only');
calculator = [1, 1;size(calculatorimage, 2), 1;size(calculatorimage, 2), size(calculatorimage, 1);1, size(calculatorimage, 1);1, 1]; 
newcalculator = transformPointsForward(tform, calculator);
figure;
imshow(seenimage);
hold on;
line(newcalculator(:, 1), newcalculator(:, 2), 'Color', 'y');
title('calculator detected');